In [1]:
import torch
import esm
import os
import pathlib
import numpy as np

???

In [5]:
model, alphabet = torch.hub.load("facebookresearch/esm:main", "esm2_t33_650M_UR50D")

Downloading: "https://github.com/facebookresearch/esm/zipball/main" to /home/damir/.cache/torch/hub/main.zip
Downloading: "https://dl.fbaipublicfiles.com/fair-esm/models/esm2_t33_650M_UR50D.pt" to /home/damir/.cache/torch/hub/checkpoints/esm2_t33_650M_UR50D.pt
Downloading: "https://dl.fbaipublicfiles.com/fair-esm/regression/esm2_t33_650M_UR50D-contact-regression.pt" to /home/damir/.cache/torch/hub/checkpoints/esm2_t33_650M_UR50D-contact-regression.pt


Downloaded pretrained model  ???

In [5]:
model, alphabet = esm.pretrained.esm1v_t33_650M_UR90S_1()

Downloading: "https://dl.fbaipublicfiles.com/fair-esm/models/esm1v_t33_650M_UR90S_1.pt" to /home/damir/.cache/torch/hub/checkpoints/esm1v_t33_650M_UR90S_1.pt


Path to the script extract.py

In [2]:
esm_scripts_path = '/home/damir/.cache/torch/hub/facebookresearch_esm_main/scripts'
extract = os.path.join(esm_scripts_path, 'extract.py')
extract

'/home/damir/.cache/torch/hub/facebookresearch_esm_main/scripts/extract.py'

In [32]:
# Using pathlib
esm_scripts_path = pathlib.Path(r'/home/damir/.cache/torch/hub/facebookresearch_esm_main/scripts')
extract = pathlib.Path.joinpath(esm_scripts_path, 'extract.py')
extract

PosixPath('/home/damir/.cache/torch/hub/facebookresearch_esm_main/scripts/extract.py')

Run the script

esm example fasta file with first 26 sequences only

In [11]:
%run "{extract}" esm1v_t33_650M_UR90S_1 ../data_test/esm/P62593_small.fasta ../data_test/dna_train/ --repr_layers 33 --include mean 

Transferred model to GPU
Read ../data_test/esm/P62593_small.fasta with 26 sequences
Processing 1 of 2 batches (14 sequences)
Processing 2 of 2 batches (12 sequences)


**small test file created for prose, train_small.fa  
it fails on a sequence longer than max. length of 1024**


In [13]:
%run "{extract}" esm1v_t33_650M_UR90S_1 ../data_test/data_fa/train_small1.fa ../data_test/data_fa/train_small1/ --repr_layers 33 --include mean 

Transferred model to GPU
Read ../data_test/data_fa/train_small1.fa with 9 sequences
Processing 1 of 2 batches (7 sequences)
Processing 2 of 2 batches (2 sequences)


ValueError: Sequence length 1060 above maximum  sequence length of 1024

the same test file, just updated header for esm format and kept only the first sequence row (length = 60)

In [28]:
%run "{extract}" esm1v_t33_650M_UR90S_1 ../data_test/data_fa/train_small1_esm.fa ../data_test/data_fa/train_small1_esm/ --repr_layers 33 --include mean 

/home/damir/miniconda3/envs/sa/lib/python3.8/site-packages/esm/pretrained.py:215: UserWarning: Regression weights not found, predicting contacts will not produce correct results.
  warnings.warn(


Transferred model to GPU
Read ../data_test/data_fa/train_small1_esm.fa with 9 sequences
Processing 1 of 1 batches (9 sequences)


Above I used pathlib for paths and some how there was a warning about regression weights???   
Below, I used os.path and no warning ???

In [30]:
%run "{extract}" esm1v_t33_650M_UR90S_1 ../data_test/data_fa/train_small1_esm.fa ../data_test/data_fa/train_small1_esm/ --repr_layers 33 --include mean 

Transferred model to GPU
Read ../data_test/data_fa/train_small1_esm.fa with 9 sequences
Processing 1 of 1 batches (9 sequences)


#### Reading embeddings

In [15]:
fn = '../data_test/data_fa/train_small1_esm/9A0LUZ11.pt'

In [16]:
torch.load(fn)

{'label': '9|A0LUZ1|1',
 'mean_representations': {33: tensor([-0.4481,  0.0098, -0.0130,  ..., -0.1554,  0.1550,  0.0034])}}

In [24]:
a = torch.load(fn)['mean_representations'][33].numpy()

a

array([-0.44807148,  0.00982585, -0.01303552, ..., -0.15544945,
        0.15500957,  0.00342662], dtype=float32)

Reading all .pt files form their folder
Names created from the fasta file.

In [42]:
for header, _seq in esm.data.read_fasta('../data_test/data_fa/train_small1_esm.fa'):
    fn= f'../data_test/data_fa/train_small1_esm/{header[1:]}.pt'
    print(fn)
    embs = torch.load(fn)
    print(embs)
    

../data_test/data_fa/train_small1_esm/1|Q6A8L0|1.pt
{'label': '1|Q6A8L0|1', 'mean_representations': {33: tensor([ 0.1052, -0.0943,  0.1146,  ...,  0.1645,  0.0593, -0.0498])}}
../data_test/data_fa/train_small1_esm/2|Q7V7T9|1.pt
{'label': '2|Q7V7T9|1', 'mean_representations': {33: tensor([-0.2922, -0.0100, -0.2274,  ..., -0.0630,  0.0109,  0.0012])}}
../data_test/data_fa/train_small1_esm/3|Q9ZUP2|1.pt
{'label': '3|Q9ZUP2|1', 'mean_representations': {33: tensor([-0.0179, -0.0302,  0.0181,  ..., -0.0794,  0.0510, -0.0168])}}
../data_test/data_fa/train_small1_esm/4|Q2JVG1|1.pt
{'label': '4|Q2JVG1|1', 'mean_representations': {33: tensor([-0.1372, -0.0579, -0.2276,  ...,  0.0754,  0.2182, -0.1280])}}
../data_test/data_fa/train_small1_esm/5|Q9K4Q3|1.pt
{'label': '5|Q9K4Q3|1', 'mean_representations': {33: tensor([ 0.1468, -0.2717, -0.1427,  ..., -0.2242, -0.1807, -0.0383])}}
../data_test/data_fa/train_small1_esm/6|Q4FV41|1.pt
{'label': '6|Q4FV41|1', 'mean_representations': {33: tensor([-0.2414

In [43]:
!tree -DhL 2 '../data_test/data_fa/train_small1_esm'

../data_test/data_fa/train_small1_esm
├── [5.8K Aug 29 14:09]  1|Q6A8L0|1.pt
├── [5.8K Aug 29 14:09]  2|Q7V7T9|1.pt
├── [5.8K Aug 29 14:09]  3|Q9ZUP2|1.pt
├── [5.8K Aug 29 14:09]  4|Q2JVG1|1.pt
├── [5.8K Aug 29 14:09]  5|Q9K4Q3|1.pt
├── [5.8K Aug 29 14:09]  6|Q4FV41|1.pt
├── [5.8K Aug 29 14:09]  7|P9WNR8|1.pt
├── [5.8K Aug 29 14:09]  8|Q5Z3Z8|1.pt
└── [5.8K Aug 29 14:09]  9|A0LUZ1|1.pt

0 directories, 9 files


In [15]:
help(esm)

Help on package esm:

NAME
    esm

DESCRIPTION
    # Copyright (c) Facebook, Inc. and its affiliates.
    #
    # This source code is licensed under the MIT license found in the
    # LICENSE file in the root directory of this source tree.

PACKAGE CONTENTS
    axial_attention
    constants
    data
    inverse_folding (package)
    modules
    multihead_attention
    pretrained
    rotary_embedding
    version

SUBMODULES
    model

VERSION
    1.0.2

FILE
    /home/damir/miniconda3/envs/sa/lib/python3.8/site-packages/esm/__init__.py




#### Conversion of csv files to fasta files

- New script that creates headers per esm 



In [1]:
# Import the script from different folder
import sys  
sys.path.append('../scripts')

import convert_csv_to_fasta_V2 as cf

acp

In [8]:
# Define paths
csv_file = '../data/acp/train_data.csv'
fasta_file = '../data/acp/train_data_V2.fa'

In [9]:
# Run the script
cf.csv_to_fasta(csv_file, fasta_file)

amp

In [4]:
# Define paths
csv_file = '../data/amp/all_data.csv'
fasta_file = '../data/amp/all_data_V2.fa'

In [5]:
# Run the script
cf.csv_to_fasta(csv_file, fasta_file)

dbp

In [6]:
# Define paths
csv_file = '../data/dna_binding/train.csv'
fasta_file = '../data/dna_binding/train_V2.fa'

In [7]:
# Run the script
cf.csv_to_fasta(csv_file, fasta_file)

dbp test

- original sequence name contents pipe ("|") character
- testing below how to trae that because pipe is used as a separator in headers.
- this give us one additional separator on which we do not want to separate

In [10]:
# Define paths
csv_file = '../data/dna_binding/test.csv'
fasta_file = '../data/dna_binding/test_V2.fa'

In [11]:
# Run the script
cf.csv_to_fasta(csv_file, fasta_file)

seq name with pipe ( | ), Q9Y6V0|2

In [19]:
# header
h = '>1284|Q9Y6V0|2|0'
# splitting on first occurance
hh = h.split('|', 1)
hh

['>1284', 'Q9Y6V0|2|0']

In [21]:
# label - target variable
h[-1]

'0'

In [22]:
# file name
h[1:]

'1284|Q9Y6V0|2|0'

In [30]:
# seq name
hh[-1][:-2]

'Q9Y6V0|2'

seq name without pipe ( | ), Q9Y6V0

In [28]:
# header
h1 = '>1284|Q9Y6V0|0'
# separate at first occurance
hh1 = h1.split('|',1)
hh1

['>1284', 'Q9Y6V0|0']

In [31]:
# label - target variable
h1[-1]

'0'

In [29]:
# file name
h1[1:]

'1284|Q9Y6V0|0'

In [33]:
# seq name
hh1[-1][:-2]

'Q9Y6V0'

### Test how esm processes 60-characters chunks

- does it read all of them or only the first one

Copied train_small1.fa to train_small1_esm_1l.fa, deleted 2 long sequences and 7 others changed to 1 line

In [10]:
%run "{extract}" esm1v_t33_650M_UR90S_1 ../data_test/data_fa/train_small1_esm_1l.fa ../data_test/data_fa/train_small1_esm_1l/ --repr_layers 33 --include mean 

Transferred model to GPU
Read ../data_test/data_fa/train_small1_esm_1l.fa with 7 sequences
Processing 1 of 1 batches (7 sequences)


In [11]:
fn1 = '../data_test/data_fa/train_small1_esm_1l/A0LUZ1.pt'
fn2 = '../data_test/data_fa/train_small1/A0LUZ1.pt'

In [16]:
a1 = torch.load(fn1)['mean_representations'][33].numpy()
a1

array([-0.68980575,  0.04476202,  0.08303404, ..., -0.15218607,
       -0.00974073,  0.10190307], dtype=float32)

In [17]:
a2 = torch.load(fn2)['mean_representations'][33].numpy()
a2

array([-0.68980575,  0.04476202,  0.08303404, ..., -0.15218607,
       -0.00974073,  0.10190307], dtype=float32)

In [23]:
np.where(a1 != a2)

(array([], dtype=int64),)

#### Reading fasta file containing 60-characters chunks seq with esm.data.read_fasta

In [24]:
for header, seq in esm.data.read_fasta('../data_test/data_fa/train_small1.fa'):
    print(f'{header}\n{seq}')


>Q6A8L0
MSGHSKWATTKHKKAAIDAKRGKLFARLIKNIEVAARLGGGDPSGNPTLYDAIQKAKKSSVPNDNITRAVKRGSGEGADAVNYETIMYEAYGPAGVAILIECLTDNRNRAVSDVRVAVTRNGGTMADGGSVQRLFQRKGVVSVSKTYEVEEGRKTETREVDEDQLMEATIDAEPEDIVDEGEVFEIISDPSAVVDVRKAVQGAGIDYDSAEVSFKPDFTQRVELEDARKLYRILDALEDLDDVQNVFSNVDIPAEVAAALDEEE
>Q7V7T9
MIGWLQGQKVEAWQQGTRQGVVLACAGVGYEVQIAPRHLSEMEHGQNTFILWIHQVQRDDGSSLFGFPERRERDMFRTLIGVSGVGPQMALALLEECQTGELVEAIVQGDLRKLCQAQGVGKRTAERLAVELRTKLAEFSCRDPGMSLVDNGVIDSHQLKDSSLHELQITLGGLGYEDLEIRRAIRAVASGAAIGASDMPESVPSIDDTDAWLRASLRWLSQEAA
>Q9ZUP2
MARILRNVYSLRSSLFSSELLRRSVVGTSFQLRGFAAKAKKKSKSDGNGSSEEGMSKKEIALQQALDQITSSFGKGSIMYLGRAVSPRNVPVFSTGSFALDVALGVGGLPKGRVVEIYGPEASGKTTLALHVIAEAQKQGGTCVFVDAEHALDSSLAKAIGVNTENLLLSQPDCGEQALSLVDTLIRSGSVDVIVVDSVAALVPKGELEGEMGDAHMAMQARLMSQALRKLSHSLSLSQTLLIFINQVRSKLSTFGGFGGPTEVTCGGNALKFYASMRLNIKRIGLIKKGEETTGSQVSVKIVKNKLAPPFRTAQFELEFGKGICKITEIIDLSIKHKFIAKNGTFYNLNGKNYHGKEALKRFLKQNESDQEELMKKLQDKLIADEAADKETESESEEEDSLRVVVSPDNTDDESPALVVGAAAVVVEAA
>Q2JVG1
MKCPRCGKQEIRVLESRSAEGGQSVRRRRECMSCGYRFTTYERIEF

#### Converting h5 file to folder with .pt files

In [3]:
import h5py
file_name = '../data_test/data_h5/train_small1_mt_avg.h5'
pt_name = '../data_test/data_h5/train_small1_mt_avg/'
pool = 'avg'

In [29]:

with h5py.File(file_name, 'r') as hf:
    for key in hf.keys():
        print(key, end=' ')
        data = hf.get(key)
        n = np.array(data)
       

A0LUZ1 P9WNR8 Q2JVG1 Q4FV41 Q5Z3Z8 Q6A8L0 Q7V7T9 Q9K4Q3 Q9ZUP2 

In [4]:
with h5py.File(file_name, 'r') as hf:
    dd = {}
    key = 'A0LUZ1'
    dd['label'] = key
    print(key)
    # data = hf.get(key)
    t = torch.tensor(hf.get(key))
    dd[f'{pool}_representations'] = {'layer': t}
    torch.save(dd, f'{key}.pt')
    print(t)

A0LUZ1
tensor([ 0.1055,  0.1127,  0.0145,  ..., -0.1284,  0.0932, -0.0319])


In [5]:
torch.load('A0LUZ1.pt')

{'label': 'A0LUZ1',
 'avg_representations': {'layer': tensor([ 0.1055,  0.1127,  0.0145,  ..., -0.1284,  0.0932, -0.0319])}}

In [50]:
tt = h5py.File(file_name, 'r')
torch.tensor(tt.get('A0LUZ1'))

tensor([ 0.1055,  0.1127,  0.0145,  ..., -0.1284,  0.0932, -0.0319])

In [53]:
a1 = torch.load(fn1) #['mean_representations'][33].numpy()
a1

{'label': 'A0LUZ1',
 'mean_representations': {33: tensor([-0.6898,  0.0448,  0.0830,  ..., -0.1522, -0.0097,  0.1019])}}

In [ ]:
torch.save()

In [ ]:
esm.pretrained.

In [16]:
def convert_h5_to_pt(file_name, pt_name, pool):
    os.makedirs(pt_name, exist_ok=True)
    with h5py.File(file_name, 'r') as hf:
        dd = {}
        for key in hf.keys():
            dd['label'] = key
            t = torch.tensor(hf.get(key))
            dd[f'{pool}_representations'] = {'layer': t}
            torch.save(dd, f'{os.path.join(pt_name, key)}.pt')

In [17]:
convert_h5_to_pt(file_name, pt_name, pool)

In [18]:
a2 = torch.load(os.path.join(pt_name, 'P9WNR8.pt'))
a2

{'label': 'P9WNR8',
 'avg_representations': {'layer': tensor([ 0.1353,  0.0226,  0.0075,  ...,  0.0060,  0.2428, -0.0336])}}